name: Generate Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out this repository (github-stats) under $GITHUB_WORKSPACE
    - uses: actions/checkout@v3

    # Set up Python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'

    # Install dependencies with pip
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    # Commit generated files to github-stats repository
    - name: Commit to the repo
      run: |
        git config --global user.name "jstrieb/github-stats"
        git config --global user.email "github-stats[bot]@jstrieb.github.io"
        git add .
        git commit -m 'Update generated files' || true
        git push

    # ---------------------------
    # New steps to update public repo
    # ---------------------------

    # Check out the target repository (e.g., your saikiransomanagoudar repo)
    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: saikiransomanagoudar/saikiransomanagoudar
        token: ${{ secrets.ACCESS_TOKEN }}
        path: target_repo

    # Copy the generated SVG files to the target repository's "generated" folder
    - name: Copy SVG files to target repository
      run: |
        mkdir -p target_repo/generated
        cp -r generated/* target_repo/generated/

    # Commit and push changes in the target repository
    - name: Commit and push changes in target repository
      working-directory: target_repo
      run: |
        git config user.name "github-stats"
        git config user.email "github-stats[bot]@jstrieb.github.io"
        git add .
        git commit -m "Update generated stats images" || echo "No changes to commit"
        git push
